[project]
name = "aoc-2025"
version = "0.1.2025"
requires-python = ">=3.12"
dependencies = [
    "rich>=14.2.0",
    "z3-solver>=4.15.4.0",
]

[tool.ruff]
line-length = 119

[dependency-groups]
dev = [
    "ipdb>=0.13.13",
    "ipython>=9.8.0",
]
